### ISSUE TITLE
Not sure what nuget package does since VS 2013 can't open the wixproj file without installing wix.

### ISSUE THREAD

**Issue by bpeikes** [akoeplinger/WiX.Toolset.NuGet#2]
How is the nuget package supposed to be used? I had installed WIX 3.8 from the official install site. I then created a WIX project under VS 2013. I thought that by adding the wix package via nuget to the project, any developer which opened the solution with this project would automatically get the WIX package. It doesn't appear that nuget packages can be associated with solutions though.

**Comment by akoeplinger** [comment]
You're correct, to open a WiX project in VS you still need to install WiX (technically only the WiX Votive plugin which provides the editing capabilities to VS, but it isn't available separately from the main WiX installer).

The main reason I created this NuGet package was to avoid installing WiX on build servers (where you might not have control over what gets installed). The build runs on the command line / MSBuild there, which works fine with the package.

As far as I know, it's not possible to add new project types / install VSIX via NuGet packages, so there is no easy way to fix this (they appear to have an old [feature request](http://nuget.codeplex.com/workitem/676) for this).

**Comment by janwilmans** [comment]
It seems this is correct, you can however install the wix VS extension, separately

https://marketplace.visualstudio.com/search?term=wix%20toolset&target=VS&category=Tools&vsVersion=&subCategory=All&sortBy=Relevance

**Comment by akoeplinger** [comment]
WiX v4 provides official NuGet packages, see https://wixtoolset.org
