### ISSUE TITLE
Can't apply to CustomAction WIX project types

### ISSUE THREAD

**Issue by shusak** [akoeplinger/WiX.Toolset.NuGet#5]
The nuget packages can't be applied to a C# CustomAction WIX project type due to the project kind check in the install ps1. It would be convenient to allow this.

**Comment by akoeplinger** [comment]
Hmm, I think this is the same issue as https://github.com/akoeplinger/WiX.Toolset.NuGet/issues/3. Can you try the workaround there?

I agree this is not ideal for extension projects, I really need to figure out a way to make this better.

**Comment by shusak** [comment]
Yes this workaround will work fine. Sorry I didn't see #3 before!
