### ISSUE TITLE
WiX v3.10.3 (Stable)

### ISSUE THREAD

**Issue by KindDragon** [akoeplinger/WiX.Toolset.NuGet#7]
Please update to latest WiX

**Comment by jozefizso** [comment]
WiX Toolset nuget package 3.10.3 was released here: https://www.nuget.org/packages/WiX.Toolset.UnofficialFork/3.10.3

**Comment by akoeplinger** [comment]
WiX v4 provides official NuGet packages, see https://wixtoolset.org
