### ISSUE TITLE
Provide WiX 3.11

### ISSUE THREAD

**Issue by jnm2** [akoeplinger/WiX.Toolset.NuGet#8]
Please update.

**Comment by jozefizso** [comment]
WiX Toolset nuget package 3.11.0 was released here: https://www.nuget.org/packages/WiX.Toolset.UnofficialFork/3.11.0

**Comment by jnm2** [comment]
It this was tracking work that you still want to do, please feel free to reopen! Otherwise, cleaning up due to inactivity.

These are staying up to date:

- https://www.nuget.org/packages/WiX.Toolset.UnofficialFork
  Thanks, @jozefizso ! (https://github.com/jozefizso/WiX.Toolset.NuGet)

- https://www.nuget.org/packages/WiX
  Thanks, @kzu! (https://github.com/kzu/WiX)
